# Put at $APPDATA\alacritty\alacritty.toml

[shell]
program = "cmd.exe"
args = [ "/C", "cd %USERPROFILE%&cmd.exe" ]

[font]
normal = { family = "IntoneMono NFM" }
size = 8.1

[window]
dimensions = { columns = 210, lines = 48 }
position = { x = 120, y = 50 }

[keyboard]
bindings = [
  { key = "Tab", mods = "Shift", chars = "\u001B[9;2u"  },
  { key = "Return", mods = "Shift", chars = "\u001B[13;2u" }
]

# Adapt cursor color so it is not hidden during nvim search-highlight.
[colors]
  cursor.text = "0xffffff"
  cursor.cursor = "0x33cc40"
  # reserve_color = "0xff33ff"
  # reserve_color = "0xcc3340"
